baseURL: https://loganchow.github.io/
defaultContentLanguage: "zh"
title: Mens et Manus
paginate: 10
theme: PaperMod

googleAnalytics: UA-138915624-1

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
enableInlineShortcodes: false

minify:
    disableXML: true
    minifyOutput: true

languages:
    zh:
        languageName: "中文"
        weight: 1
        menu:
            main:
                - name: 归档
                  url: archives
                  weight: 5
                - name: 搜索
                  url: search/
                  weight: 10
                - name: 标签
                  url: tags/
                  weight: 10
                - name: 分类
                  url: categories/
                  weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Mens et Manus
    description: "绵绵春雨懒洋洋，故友不来不起床。"
    # keywords: [Blog, Portfolio, PaperMod]
    author: Me
    # author: ["Me", "You"] # multiple authors
    # images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    # disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    # disableSpecial1stPost: false
    disableScrollToTop: false
    # comments: false
    #hidemeta: false
    # hideSummary: false
    showToc: false
    # tocopen: false

    # assets:
    #     # disableHLJS: true # to disable highlight.js
    #     # disableFingerprinting: true
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    label:
        text: "Logan's Space"
        # icon: /apple-touch-icon.png
        # iconHeight: 35

    # profile-mode
    # profileMode:
    #     enabled: false # needs to be explicitly set
    #     title: Eureka
    #     subtitle: "This is subtitle"
    #     imageUrl: "#"
    #     imageWidth: 120
    #     imageHeight: 120
    #     imageTitle: my image
    #     buttons:
    #         - name: Archives
    #           url: archives
    #         - name: Tags
    #           url: tags

    # home-info mode
    homeInfoParams:
        Title: "你好，朋友! \U0001F44B 欢迎来到我的个人空间 "
        Content: >
            做难事必有所得。

    socialIcons:
        - name: linkedin
          url: "https://www.linkedin.com/in/zhouyichen110/"
        - name: github
          url: "https://github.com/loganchow"

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"
    #     bing:
    #         SiteVerificationTag: "XYZabc"
    #     yandex:
    #         SiteVerificationTag: "XYZabc"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/loganchow/loganchow.github.io/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: categories
          name: categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20
        - identifier: example
          name: example.org
          url: https://example.org
          weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai